apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desafio-02
  template:
    metadata:
      labels:
        app: desafio-02
    spec:
      containers:
      - name: copilot-challenge-3
        image: copilot-challenge-3.jar:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: 127.0.0.1:3306
        - name: DB_NAME
          value: copilot
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: root