server:
   port: ${APP_PORT:8080}

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/copilot?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      javax:
        persistence:
          validation:
            mode: none
